import Head from "next/head";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>Hello</main>
    </div>
  );
}

// export async function getStaticProps(context) {
//   try {
//     const req = await fetch("https://api.thecatapi.com/v1/breeds");
//     const data = await req.json();
//     console.log(data);
//     return {
//       props: { data },
//     };
//   } catch (error) {
//     console.log(error);
//   }
// }
